.gitmodules
Makefile
variant-box/pi-setup.sh
variant-zero/pi-setup.sh

This PR replaces #10 
@nolim1t feel free to test out if this works. I'll be doing that tomorrow.

Replace pi-init2 with pi-init3

---

variant-box/pi-setup.sh

change the firewall to allow for lightning.
Also add screen and vim to the install (some people prefer vim over nano .. ditto for screen vs tmux)

Changes to firewall for the box to allow for lightning

---

variant-alpine/README.md

Update README to make the tarball file more consistent with the build version

Update README to make it more consistent

---

.gitignore

Ignore more files that are sensitive for Alpine

Ignore more files that are sensitive for Alpine

---

.gitignore
variant-alpine/make_img.sh

Add a few pre-conditions for the make_img.sh script. Also add some more stuff into .gitignore

Add a few pre-conditions for the make_img.sh script

---

etc/init.d/lncm-post

Add conditionals for lncm post to ensure that it doesn't run without some checks

Add conditionals for lncm post

---

etc/apk/protected_paths.d/lbu.list

Add lncm-post to protected paths list

Add lncm-post to protected paths list

---

etc/init.d/bitcoind-install

Add bitcoind install to start work on #49

Add bitcoind install placeholder

---

etc/init.d/lncm-post

Fix up if statements in lncm-post

Fix up lncm-post file

---

etc/apk/protected_paths.d/lbu.list

Add config files to protected paths

---

etc/init.d/lncm-post

Fix up lncm-post so it now configures all the files correctly

Fix up lncm-post so it now configures all the files correctly

---

home/lncm/.lnd/lnd.conf
home/lncm/compose/docker-compose.yml

This should resolve issue #48 
Also made some changes to the config file, mainly removing pathnames as it should use whats in the container

Docker compose with LND inside - all I want for christmas is a lightning box!

---

etc/init.d/lncm

Fix for rebooting and also added some extra debugging

---

home/lncm/compose/docker-compose.yml

Update bitcoind image version in docker-compose

---

.gitignore

Ignore the README file generated by the apkovl generation script

Ignore the README file generated by the apkovl generation script

---

etc/apk/protected_paths.d/lbu.list
etc/apk/repositories
etc/init.d/lncm-post
etc/tor/torrc

Start work for issue #69 
Currently testing this.
**Current State** Not ready for merging yet

Add TOR to alpine install

---

etc/init.d/docker-compose

Change exit statuses so that the service manager reports correctly

Change exit statuses in docker-compose so that the service manager reports correctly

---

README.md

Add hardware requirements to README file

Hardware requirements

---

etc/init.d/lncm-post

This ensures prune=% and externalip get set correctly
Also closes #92

Backup & replace existing bitcoind, lnd configs

---

etc/tor/torrc

Some nodes have trouble connecting to V3 addresses.
This pull request addresses that issue

Tor V2 compatibility

---

home/lncm/crontab

Add another change to crontab, and insert a line break at the end also (didn't seem to get executed.
Also deciding to log the output to a file too. 
Change execution time to run every minute

Add another change to crontab

---

etc/init.d/lncm-post

Add tor to default runlevels so that it restarts

Add tor to default runlevels

---

home/lncm/compose/docker-compose.yml

Latest invoicer with no basic auth other than /api/history

---

usr/local/sbin/mana

Because theres a directive in the docker-compose to automatically restart some services, have added some more stuff to help it stop nicely.

Stop more gracefully patch to management script

---

.gitignore
README.md
etc/apk/protected_paths.d/lbu.list
make_img.sh

This patch will allow for a more secure default install (Closes #88) whenever merged.
Currently testing this out first.

(COMPLETE) Allow for a more secure default install

---

.gitignore

Restore gitinore changes that was removed as we need those lines still so we don't commit wifi creds.
Will also add some more safety checks in there too

Restore gitinore changes that was removed

---

.gitignore
README.md
etc/apk/protected_paths.d/lbu.list

Some more additional supporting docs for create wallet, as well as putting those files in the .gitignore

Create wallet helper/supporting docs

---

home/lncm/nginx/conf.d/default.conf

Fix up proxy pass, and also add CORS in

Fix up nginx config in 3.9.0 branch

---

home/lncm/compose/docker-compose.yml
home/lncm/lnd/lnd.conf

This is based on the cube 7 changes today

[3.9.0 patch] Fix up lnd.conf in the new branch

---

home/lncm/lnd/lnd.conf
usr/local/sbin/update-lnd-tor-ipaddress.sh

To work in conjunction with PR https://github.com/lncm/pi-factory/pull/179

helper utility to fix up the IP address in LND config (as well as modified LND conf)

---

usr/local/sbin/lncm-usb

Fix up issue where swap isnt turning on

Fix up issue where SWAP isn't turning on

---

etc/init.d/lncm-post
etc/tor/torrc

Cleanup and rename tor hidden services filesystem structure
Thoughts?

Rename tor hidden services

---

usr/local/sbin/lncm-getinfo.py

Sample template python script for getting the info from LND directly so people can use this as a basis for doing other stuff from it.
Currently this just does the basic ```lncli getinfo```, but can be extended to other stuff. Using part of this script in another script in #185  (https://github.com/lncm/pi-factory/pull/185/commits/f174393c29297c96ccd7f164ea9b32844971bcdc)

Sample template script for getting the info from LND directly

---

README.md

Added some basic security guidelines into README so that people know how to change all the default passwords.

Added some basic security guidelines into README

---

etc/init.d/docker-compose

Docker compose checks to ensure that paths are mounted correctly and files are there. just to ensure robustness.
Will also put this into #185 as well

Docker compose checks to ensure that paths are mounted correctly and files are there

---

home/lncm/invoicer/invoicer.conf

Add invoicer config based on docker-compose settings in preparation for https://github.com/lncm/invoicer/commit/4bead5b0a4a59ad90f39e8cd9ff71cf6c6706fdd
* Update rewrite script 
* Copy to /media/important

[TO TEST] [To: 3.9.0] Add new invoicer config

---

home/lncm/compose/clearnet/docker-compose.yml
home/lncm/compose/tor/docker-compose.yml

Update LND to 0.6 (Closes #207) and also remove bridged network.

Update LND, remove bridged network

---

README.md
Vagrantfile
docs/README.md
make_img.sh

This fixes the remaining issue with Vagrant under Ubuntu, simplifies the configuration and adds instructions to the readme.

Vagrant complete

---

etc/nginx/conf.d/default.conf

Currently /wifi endpoint isnt working.  Thats because of the last location / redirect which possibly messes it up.

Fix up nginx.conf so that both POS and WIFI is working

---

etc/init.d/docker-compose

Make startup error message more meaningful

Make error message more meaningful (/etc/init.d/docker-compose)

---

etc/init.d/lncm-post

Fix up docker-compose install on master branch.. Currently explicitly installing **1.23.2**

Fix up docker-compose install on master branch

---

.gitignore

Add README.* to gitignore

---

home/lncm/invoicer/invoicer.conf

First step for preparing invoicer config for updating to the latest.
Next step is to copy the file into /media/important/important/invoicer and also to write in the bitcoind password using noma utility

Prepare invoicer config for updating to the latest

---

etc/nginx/conf.d/default.conf

Apply https://github.com/lncm/pi-factory/pull/221 to v0.5 branch

Same nginx config fix to master as #221

---

usr/local/sbin/lncm-usb

Fix up swap so its enabled at boot. Thanks @noaho

Fix up swap so its enabled at boot

---

home/lncm/compose/clearnet/docker-compose.yml
home/lncm/compose/tor/docker-compose.yml

Update LND to v0.7.0 on docker-compose

---

CONTRIBUTING.md

Contribution guidelines draft

---

home/lncm/compose/clearnet/docker-compose.yml
home/lncm/compose/tor/docker-compose.yml

Add in LND 0.7.1 neutrino to pi-factory master

(In Testing) Add in LND 0.7.1 neutrino to master

---

home/lncm/compose/tor/docker-compose.yml

Update Invoicer to 0.5.1 on pi-factory

Update invoicer to 0.5.1

---

home/lncm/compose/tor/docker-compose.yml

Update composefile to use LND with some more other flags enabled

---

etc/apk/protected_paths.d/lbu.list
etc/init.d/wpa_supplicant.alt

Sometimes iotwifi fails so we need a fallback implemented. Calling it alt in case it gets overwritten
Add WPA Supplicant file which detects a wpa_supplicant file inside the FAT partition in case iotwifi fails

WPA Supplicant fallback for iotwifi

---

.github/workflows/release.yml

Add github actions for release to pi-factory

Add Release Workflow to pi-factory

---

etc/init.d/lncm

Should be ```chmod``` not ```chown```

Fix up typo in create_swap() on make_img.sh

---

.github/workflows/release.yml

Change release file to only release the zip

Change release file to only release the zip

---

etc/tor/torrc

Add in SSHD to TORRC by default

Add SSHD to TORRC by default
